common:
  roles:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: '*'

mediaServiceRole:
  name: ${env:APP_ENV}-${env:APP_NAME}-media-service-role
  roles:
    - Effect: 'Allow'
      Action:
        - s3:*
      Resource:
        - arn:aws:s3:::${env:APP_S3_BUCKET}/*