export class RepoNames {
  static USER_REPOSITORY = 'USER_REPOSITORY';
  static JOB_REPOSITORY = 'JOB_REPOSITORY';
  static APPLICATION_REPOSITORY = 'APPLICATION_REPOSITORY';
  static TASK_REPOSITORY = 'TASK_REPOSITORY';
}
