export class RepoNames {
  static USER_REPOSITORY = 'USER_REPOSITORY';
  static JOB_REPOSITORY = 'JOB_REPOSITORY';
  static APPLICATION_REPOSITORY = 'APPLICATION_REPOSITORY';
  static TASK_REPOSITORY = 'TASK_REPOSITORY';
  static TASK_UPDATE_HISTORY_REPOSITORY = 'TASK_UPDATE_HISTORY_REPOSITORY';
  static TASK_ETA_UPDATE_HISTORY_REPOSITORY =
    'TASK_ETA_UPDATE_HISTORY_REPOSITORY';
  static TASK_STATUS_UPDATE_HISTORY_REPOSITORY =
    'TASK_STATUS_UPDATE_HISTORY_REPOSITORY';
}
